/**
 * Shared domain types for the Meeting Assistant frontend.
 *
 * These mirror the Pydantic models defined in the FastAPI backend (Phase 4).
 * Keep this file as the single source of truth for TypeScript consumers —
 * avoid duplicating these shapes in individual components or Zustand stores.
 */

// ---------------------------------------------------------------------------
// Meeting
// ---------------------------------------------------------------------------

/**
 * Lifecycle states for a Meeting record.
 *
 * State machine (happy path):
 *   created → recording → recorded → transcribing → transcribed
 *     → summarizing → done
 *
 * Any state can transition to 'error'.
 */
export type MeetingStatus =
  | 'created'
  | 'recording'
  | 'recorded'
  | 'transcribing'
  | 'transcribed'
  | 'summarizing'
  | 'done'
  | 'error'

export interface Meeting {
  /** UUID generated by the backend on creation */
  id: string
  title: string
  /** ISO 8601 UTC timestamp */
  created_at: string
  /** Total recording length in seconds; null until the recording is finalised */
  duration_s: number | null
  /** Absolute path to the raw audio file on the local filesystem */
  audio_path: string | null
  /** Absolute path to the plain-text transcript file */
  transcript_path: string | null
  /** Absolute path to the markdown summary file */
  summary_path: string | null
  /** Full transcript text — populated after transcription completes */
  transcript: string | null
  /** Full summary text — populated after summarization completes */
  summary: string | null
  /** Key into the prompts.yaml file used for summarization */
  prompt_key: string | null
  status: MeetingStatus
  /** Human-readable error description; non-null only when status === 'error' */
  error_msg: string | null
}

// ---------------------------------------------------------------------------
// Job (background processing — streamed via WebSocket)
// ---------------------------------------------------------------------------

/**
 * Represents an in-flight background processing job.
 *
 * The backend emits Job updates over the WebSocket at /ws.
 * The frontend uses these to drive progress indicators without polling REST.
 */
export interface Job {
  job_id: string
  meeting_id: string
  /**
   * Granular stage within the job pipeline:
   *   transcribing → cleaning → summarizing → done
   * 'error' is terminal.
   */
  stage: 'transcribing' | 'cleaning' | 'summarizing' | 'done' | 'error'
  /** 0–100 progress percentage */
  progress: number
  /** Human-readable status message for display in the UI */
  message: string
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

/**
 * User-configurable settings, persisted by the backend and exposed via
 * GET /settings and PATCH /settings.
 */
export interface Settings {
  openai_api_key: string
  /** Whisper model size — larger = more accurate but slower */
  whisper_model: 'tiny' | 'base' | 'small' | 'medium' | 'large'
  /** PyAudio device index; -1 means use the system default */
  audio_device_index: number
  /** Directory where recordings and outputs are saved */
  output_dir: string
  /** Default prompt key from prompts.yaml */
  default_prompt_key: string
  theme: 'light' | 'dark'
}

// ---------------------------------------------------------------------------
// AudioDevice
// ---------------------------------------------------------------------------

/**
 * A system audio input device as reported by PyAudio.
 * Populated by GET /audio-devices.
 */
export interface AudioDevice {
  index: number
  name: string
}
